global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "payments-api"
    static_configs:
      - targets: ["host.docker.internal:8000"]

  - job_name: "ledger-worker"
    static_configs:
      - targets: ["host.docker.internal:8001"]
